---
dependency:
  name: galaxy
driver:
  name: docker
  provider:
    name: docker
lint:
  name: yamllint
platforms:
  - name: {{ cookiecutter.role_name }}-ubuntu-1804
    image: ubuntu:18.04
    dockerfile: Dockerfile.j2
    pre_build_image: False
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: docker-ubuntu-1804
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: goss
  lint:
    name: yamllint
