---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
  provider:
    name: docker
lint:
  name: yamllint
platforms:
  - name: {{ cookiecutter.role_name }}-centos-76
    image: centos:7.6.1810
    dockerfile: ../resources/Dockerfile.j2
    privileged: true
    pre_build_image: false
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /tmp
    command: "/usr/sbin/init"
    environment:
      container: docker
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
  log: true
  playbooks:
    vagrant:
      prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/playbook.yml
    verify: ../resources/playbooks/verify.yml
  lint:
    name: ansible-lint
verifier:
  name: goss
  directory: ../resources/tests
  lint:
    name: yamllint
