---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
  provider:
    name: docker
lint:
  name: yamllint
platforms:
  - name: {{ cookiecutter.role_name }}-debian-10
    image: debian:10
    dockerfile: ../resources/Dockerfile.j2
    pre_build_image: False
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    environment:
      container: docker
provisioner:
  name: ansible
  extra_vars:
    ansible_python_interpreter: /usr/bin/python3
  log: True
  playbooks:
    vagrant:
      prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/playbook.yml
    verify: ../resources/playbooks/verify.yml
  lint:
    name: ansible-lint
verifier:
  name: goss
  directory: ../resources/tests
  lint:
    name: yamllint
