---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
  provider:
    name: docker
lint:
  name: yamllint
platforms:
  - name: {{ cookiecutter.role_name }}-rhel-7
    image: ubi
    registry:
      url: registry.access.redhat.com/ubi7
    dockerfile: ../resources/Dockerfile.j2
    pre_build_image: False
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment:
      container: docker
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
  log: True
  playbooks:
    vagrant:
      prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/playbook.yml
    verify: ../resources/playbooks/verify.yml
  lint:
    name: ansible-lint
verifier:
  name: goss
  directory: ../resources/tests
  lint:
    name: yamllint
